In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.pyplot import title

In [2]:
data = pd.read_csv(r'C:\Users\FARHAD\PycharmProjects\GithubCV\recommandation_systems_TMDB\Data\clean_data.csv')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Unnamed: 0            4803 non-null   int64  
 1   budget                4803 non-null   int64  
 2   genres                4803 non-null   object 
 3   id                    4803 non-null   int64  
 4   keywords              4803 non-null   object 
 5   original_language     4803 non-null   object 
 6   original_title        4803 non-null   object 
 7   overview              4800 non-null   object 
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object 
 10  release_date          4802 non-null   object 
 11  revenue               4803 non-null   int64  
 12  runtime               4801 non-null   float64
 13  spoken_languages      4803 non-null   object 
 14  tagline               3959 non-null   object 
 15  vote_average         

In [13]:
data['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [8]:
data['overview'].isnull().sum()

np.int64(3)

In [17]:
data['overview'] = data['overview'].fillna('')

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [19]:
tfv = TfidfVectorizer(min_df=3, max_features=None, ngram_range=(1, 3), stop_words='english')

In [25]:
tfv_matrix = tfv.fit_transform(data['overview'])
tfv_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 121480 stored elements and shape (4803, 9919)>

In [27]:
# getting TF-IDF matrix of first entry of overview..
# Return a array representation
tfv_matrix.toarray()[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [28]:
# lets transpose matrix
tfv_matrix[0].T.toarray()

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [29]:
X = tfv_matrix.toarray()

In [30]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,...,9909,9910,9911,9912,9913,9914,9915,9916,9917,9918
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4799,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4800,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [31]:
from sklearn.metrics.pairwise import sigmoid_kernel

In [32]:
sig = sigmoid_kernel(tfv_matrix, tfv_matrix)

In [34]:
sig[0]

array([0.76163649, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159416,
       0.76159416])

In [37]:
index = data.index
index

RangeIndex(start=0, stop=4803, step=1)

In [38]:
title = data['original_title']

In [39]:
title[4802]

'My Date with Drew'

In [41]:
indices = pd.Series(data.index, index=data['original_title'])
indices

original_title
Avatar                                         0
Pirates of the Caribbean: At World's End       1
Spectre                                        2
The Dark Knight Rises                          3
John Carter                                    4
                                            ... 
El Mariachi                                 4798
Newlyweds                                   4799
Signed, Sealed, Delivered                   4800
Shanghai Calling                            4801
My Date with Drew                           4802
Length: 4803, dtype: int64

In [47]:
#sort similarity values in ascending order

sigma_scores=sorted(list(enumerate(list(sig[indices['Avatar']]))),key=lambda x:x[1],reverse=True)
sigma_scores

[(0, np.float64(0.76163649309625)),
 (1341, np.float64(0.7616030155858681)),
 (634, np.float64(0.7616028561141562)),
 (3604, np.float64(0.761601930611584)),
 (2130, np.float64(0.7616015339622925)),
 (775, np.float64(0.7616011086528326)),
 (529, np.float64(0.7615996114069044)),
 (151, np.float64(0.7615991171152051)),
 (311, np.float64(0.7615990624497703)),
 (847, np.float64(0.7615987706430224)),
 (570, np.float64(0.7615986450599548)),
 (942, np.float64(0.7615984376900236)),
 (36, np.float64(0.761597988130195)),
 (1610, np.float64(0.7615979793934843)),
 (3070, np.float64(0.7615978406764746)),
 (1033, np.float64(0.7615978182403835)),
 (2628, np.float64(0.7615977834088159)),
 (1784, np.float64(0.7615977150705628)),
 (2578, np.float64(0.7615976778191441)),
 (150, np.float64(0.7615976453752452)),
 (3724, np.float64(0.7615975951237102)),
 (1013, np.float64(0.761597590729192)),
 (4211, np.float64(0.7615975631290405)),
 (1213, np.float64(0.7615975380289366)),
 (1345, np.float64(0.76159745490752

In [48]:
sigma_scores[1:11]

[(1341, np.float64(0.7616030155858681)),
 (634, np.float64(0.7616028561141562)),
 (3604, np.float64(0.761601930611584)),
 (2130, np.float64(0.7616015339622925)),
 (775, np.float64(0.7616011086528326)),
 (529, np.float64(0.7615996114069044)),
 (151, np.float64(0.7615991171152051)),
 (311, np.float64(0.7615990624497703)),
 (847, np.float64(0.7615987706430224)),
 (570, np.float64(0.7615986450599548))]

In [51]:
# to access index of above list

ind=[index[0] for index in sigma_scores[1:11]]
ind

[1341, 634, 3604, 2130, 775, 529, 151, 311, 847, 570]

In [52]:
data['original_title'].iloc[ind]


1341                Obitaemyy Ostrov
634                       The Matrix
3604                       Apollo 18
2130                    The American
775                        Supernova
529                 Tears of the Sun
151                          Beowulf
311     The Adventures of Pluto Nash
847                         Semi-Pro
570                           Ransom
Name: original_title, dtype: object

In [53]:
#define function that will give recommendations

def give_rec(title,model):

    idx=indices[title]

    model_scores=list(enumerate(list(model[indices[idx]])))

    model_scores=sorted(model_scores,key=lambda x:x[1],reverse=True)

    model_scores=model_scores[1:11]

    movie_indices=[index[0] for index in model_scores]

    return data['original_title'].iloc[movie_indices]

In [54]:
# Testing our content-based recommendation system with the film 'Avatar'

give_rec('Avatar',sig)

C:\Users\FARHAD\AppData\Local\Temp\ipykernel_14732\371111120.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  model_scores=list(enumerate(list(model[indices[idx]])))


1341                Obitaemyy Ostrov
634                       The Matrix
3604                       Apollo 18
2130                    The American
775                        Supernova
529                 Tears of the Sun
151                          Beowulf
311     The Adventures of Pluto Nash
847                         Semi-Pro
570                           Ransom
Name: original_title, dtype: object